# Generated by Django 5.1.2 on 2024-11-18 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField()),
                ('intensity', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CrossFitTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=50)),
                ('rounds', models.PositiveIntegerField()),
                ('time_cap', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlexibilityTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField()),
                ('stretch_type', models.CharField(choices=[('Static', 'Static'), ('Dynamic', 'Dynamic')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('recovery_type', models.CharField(choices=[('Active', 'Active'), ('Passive', 'Passive'), ('Psychological', 'Psychological')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], max_length=20)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('goal', models.CharField(choices=[('Lose', 'Lose Weight'), ('Gain', 'Gain Weight'), ('Maintain', 'Maintain Weight')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_budget', models.IntegerField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfitapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BodyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_metrics', to='myfitapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ResistanceTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=50)),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistance', to='myfitapp.musclegroup')),
                ('current_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistance', to='myfitapp.traininglevel')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalWorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cardio_trainings', models.ManyToManyField(blank=True, to='myfitapp.cardiotraining')),
                ('crossfit_trainings', models.ManyToManyField(blank=True, to='myfitapp.crossfittraining')),
                ('flexibility_trainings', models.ManyToManyField(blank=True, to='myfitapp.flexibilitytraining')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='myfitapp.profile')),
                ('recoveries', models.ManyToManyField(blank=True, to='myfitapp.recovery')),
                ('resistance_trainings', models.ManyToManyField(blank=True, to='myfitapp.resistancetraining')),
            ],
        ),
        migrations.AddField(
            model_name='crossfittraining',
            name='current_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossfit', to='myfitapp.traininglevel'),
        ),
        migrations.AddField(
            model_name='cardiotraining',
            name='current_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardio', to='myfitapp.traininglevel'),
        ),
        migrations.CreateModel(
            name='UserFoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(default='unknown', max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('protein_intake', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('fat_intake', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('carbs_intake', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to='myfitapp.profile')),
            ],
        ),
    ]
