# Generated by Django 5.1.2 on 2024-11-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resistancetraining',
            name='reps',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resistancetraining',
            name='sets',
            field=models.CharField(max_length=50),
        ),
    ]
