# Generated by Django 5.1.2 on 2024-11-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfitapp', '0002_alter_resistancetraining_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resistancetraining',
            name='weight',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
