# Generated by Django 5.1.2 on 2024-11-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfitapp', '0003_alter_resistancetraining_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resistancetraining',
            name='weight',
            field=models.CharField(max_length=500),
        ),
    ]
