import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black font-sans`}>
        <div className="fixed inset-0 z-0 overflow-hidden pointer-events-none">
          <div className="absolute top-1/2 right-1/2 w-[450px] h-80 bg-blue-500/60 rounded-full blur-[128px] animate-pulse"></div>
          <div className="absolute top-1/2 left-1/2 w-[450px] h-80 bg-cyan-500/60 rounded-full blur-[128px] animate-pulse delay-100"></div>
          <div className="absolute bottom-1/2 left-1/2 w-[450px] h-80 bg-blue-500/60 rounded-full blur-[128px] animate-pulse delay-200"></div>
          <div className="absolute bottom-1/2 right-1/2 w-[450px] h-80 bg-cyan-500/60 rounded-full blur-[128px] animate-pulse delay-300"></div>
          <div
            className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.05)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.05)_1px,transparent_1px)] bg-[size:64px_64px] opacity-20">
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
